"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { categories, formatDate, getCategory, getCategoryPosts, getExcerpt, getPostBySlug, getPostCategory, getSortedPosts, type Post } from "@/lib/content";

type SiteShellProps = { route: string[]; adminAllowed?: boolean };
const navItems = [{ href: "/", label: "홈" }, { href: "/all", label: "모든 글" }, { href: "/toc", label: "목차" }, { href: "/about", label: "소개" }];

export function SiteShell({ route, adminAllowed = false }: SiteShellProps) {
  const [dark, setDark] = useState(false);
  useEffect(() => { const stored = window.localStorage.getItem("killmkill97-theme"); const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches; setDark(stored ? stored === "dark" : prefersDark); }, []);
  useEffect(() => { document.documentElement.classList.toggle("dark", dark); window.localStorage.setItem("killmkill97-theme", dark ? "dark" : "light"); }, [dark]);
  return <div className="site-frame"><Header dark={dark} onToggleTheme={() => setDark((value) => !value)} /><main className="site-main"><div className="archive-rule" aria-hidden="true" />{route.length === 0 ? <HomePage /> : null}{route[0] === "all" ? <AllPostsPage /> : null}{route[0] === "toc" ? <TocPage /> : null}{route[0] === "about" ? <AboutPage /> : null}{route[0] === "category" && route[1] ? <CategoryPage categoryId={route[1]} /> : null}{route[0] === "post" && route[1] ? <PostPage slug={route[1]} /> : null}{route[0] === "admin" ? <AdminPreview allowed={adminAllowed} /> : null}{!isKnownRoute(route) ? <NotFoundPage /> : null}</main><footer className="site-footer"><span>killmkill97 archive</span><span>그냥 내가 만든 거랑 생각난 거 올리는 곳</span></footer></div>;
}
function isKnownRoute(route: string[]) { if (route.length === 0) return true; if (["all", "toc", "about", "admin"].includes(route[0])) return route.length === 1; if (["category", "post"].includes(route[0])) return Boolean(route[1]) && route.length === 2; return false; }
function Header({ dark, onToggleTheme }: { dark: boolean; onToggleTheme: () => void }) { return <header className="site-header"><Link className="brand" href="/" aria-label="killmkill97 홈"><span className="brand-mark" aria-hidden="true">k/</span><span>killmkill97</span></Link><nav className="top-nav" aria-label="주요 메뉴">{navItems.map((item) => <Link key={item.href} href={item.href}>{item.label}</Link>)}</nav><button className="theme-toggle" type="button" onClick={onToggleTheme} aria-label={dark ? "라이트 모드로 바꾸기" : "다크 모드로 바꾸기"}><span aria-hidden="true">{dark ? "☼" : "☾"}</span><span className="theme-label">{dark ? "밝게" : "어둡게"}</span></button></header>; }
function HomePage() { const recent = getSortedPosts().slice(0, 6); const categoryCount = categories.filter((category) => !category.parentId).length; return <div className="page-stack home-page"><section className="intro-block"><p className="eyebrow">PERSONAL ARCHIVE / 2026—</p><h1>내가 만든 거랑<br /><em>생각난 거</em> 올리는 곳.</h1><p className="intro-copy">수학도 하고, 마크도 하고, 게임도 만들고, 가끔은 그냥 이상한 걸 발견함.</p><div className="intro-meta"><span>posts {getSortedPosts().length}</span><span>categories {categoryCount}</span><span>last updated {formatDate(recent[0].updatedAt)}</span></div></section><section className="section-block"><div className="section-heading"><div><p className="eyebrow">RECENTLY WRITTEN</p><h2>최근 글</h2></div><Link className="text-link" href="/all">모든 글 보기 <span>↗</span></Link></div><div className="post-list">{recent.map((post) => <PostCard key={post.id} post={post} />)}</div></section><section className="home-scrap"><span className="scrap-label">메모</span><p>이번 주엔 또 뭘 만들지 모르겠음. 일단 기록은 해두자.</p><span className="scrap-mark">*</span></section></div>; }
function AllPostsPage() { const [query, setQuery] = useState(""); const [order, setOrder] = useState<"newest" | "oldest">("newest"); const postsForPage = useMemo(() => { const normalized = query.toLowerCase().trim(); return getSortedPosts(order).filter((post) => !normalized || `${post.title} ${post.content} ${post.tags.join(" ")}`.toLowerCase().includes(normalized)); }, [order, query]); return <div className="page-stack"><PageIntro eyebrow="ALL POSTS" title="모든 글" copy="분류 상관없이 적어둔 것들을 시간순으로 모아봄." /><div className="list-tools"><label className="search-box"><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="제목이나 내용 검색" aria-label="제목이나 내용 검색" /></label><select value={order} onChange={(event) => setOrder(event.target.value as "newest" | "oldest")} aria-label="정렬 순서"><option value="newest">최신순</option><option value="oldest">오래된순</option></select></div><p className="result-count">{postsForPage.length}개의 글{query ? ` · '${query}' 검색 결과` : ""}</p><div className="post-list">{postsForPage.length ? postsForPage.map((post) => <PostCard key={post.id} post={post} />) : <EmptyState text="검색 결과가 없음. 다른 단어로 찾아보셈." />}</div></div>; }
function TocPage() { const roots = categories.filter((category) => !category.parentId); return <div className="page-stack"><PageIntro eyebrow="TABLE OF CONTENTS" title="목차" copy="분류는 나중에 마음대로 바꿀 수 있게 데이터로 관리 중." /><div className="toc-grid">{roots.map((category) => { const children = categories.filter((item) => item.parentId === category.id); return <section className="toc-group" key={category.id}><Link href={`/category/${category.id}`} className="toc-root"><span className="category-dot" style={{ backgroundColor: category.accent }} />{category.name}<span className="toc-arrow">↗</span></Link><p>{category.description}</p>{children.length ? <ul>{children.map((child) => <li key={child.id}><Link href={`/category/${child.id}`}>{child.name}<span>{getCategoryPosts(child.id).length}</span></Link></li>)}</ul> : <span className="toc-empty">아직 하위 분류 없음</span>}</section>; })}</div></div>; }
function CategoryPage({ categoryId }: { categoryId: string }) { const category = getCategory(categoryId); const categoryPosts = category ? getSortedPosts().filter((post) => getCategoryPosts(category.id).some((item) => item.id === post.id)) : []; if (!category) return <NotFoundPage />; return <div className="page-stack"><PageIntro eyebrow="CATEGORY" title={category.name} copy={category.description} /><div className="category-toolbar"><Link className="back-link" href="/toc">← 목차로</Link><span>{categoryPosts.length}개의 글</span></div><div className="post-list">{categoryPosts.length ? categoryPosts.map((post) => <PostCard key={post.id} post={post} />) : <EmptyState text="아직 이 분류에 적어둔 글이 없음." />}</div></div>; }
function PostPage({ slug }: { slug: string }) { const post = getPostBySlug(slug); if (!post) return <NotFoundPage />; const category = getPostCategory(post); const sorted = getSortedPosts(); const index = sorted.findIndex((item) => item.id === post.id); const previous = sorted[index + 1]; const next = sorted[index - 1]; return <article className="post-page"><div className="post-breadcrumb"><Link href="/">홈</Link><span>›</span><Link href={`/category/${category?.id ?? post.category}`}>{category?.name ?? post.category}</Link><span>›</span><span>{post.tags[0]}</span></div><header className="post-header"><p className="eyebrow">{formatDate(post.createdAt)} · {category?.name}</p><h1>{post.title}</h1><div className="tag-row">{post.tags.map((tag) => <span key={tag}>#{tag}</span>)}</div></header><div className="post-divider" /><MarkdownContent source={post.content} /><div className="post-footer-note">댓글로 의견 남겨주세요. <small>(진짜 댓글창은 아직 없음)</small></div><div className="post-navigation"><PostNavLink label="이전 글" post={previous} direction="left" /><PostNavLink label="다음 글" post={next} direction="right" /></div></article>; }
function PostNavLink({ label, post, direction }: { label: string; post?: Post; direction: "left" | "right" }) { return post ? <Link className={`post-nav-link ${direction}`} href={`/post/${post.slug}`}><span>{direction === "left" ? "←" : "→"}</span><small>{label}</small><strong>{post.title}</strong></Link> : <span className="post-nav-link disabled"><span>{direction === "left" ? "←" : "→"}</span><small>{label}</small><strong>없음</strong></span>; }
function AboutPage() { return <div className="page-stack about-page"><PageIntro eyebrow="ABOUT THIS PLACE" title="소개" copy="대단한 포트폴리오는 아니고, 그냥 뭔가를 만들면서 남겨두는 개인 홈페이지." /><div className="about-grid"><div><p>사이트 주인은 <strong>killmkill97</strong>임.</p><p>수학, 마인크래프트, 지메, Numerical Ascension 같은 걸 건드리고 있음. 완성된 결과보다 만들다가 생긴 생각이나 실패한 것도 여기에 적어둘 예정.</p></div><dl><div><dt>여기서 하는 일</dt><dd>만들기 · 기록하기 · 다시 뜯어고치기</dd></div><div><dt>글 쓰는 방식</dt><dd>Markdown 기반, 편한 말투</dd></div><div><dt>댓글</dt><dd>아직 없음. 의견은 어딘가로 보내주셈</dd></div></dl></div><Link className="text-link" href="/all">글 보러 가기 <span>↗</span></Link></div>; }
function AdminPreview({ allowed }: { allowed: boolean }) { const [preview, setPreview] = useState(false); const [title, setTitle] = useState(""); const [category, setCategory] = useState(categories[0].id); const [tags, setTags] = useState(""); const [body, setBody] = useState(""); if (!allowed) return <div className="page-stack admin-placeholder"><PageIntro eyebrow="PRIVATE AREA" title="관리자" copy="이 공간은 사이트 주인만 들어올 수 있음." /><div className="admin-box"><span className="status-stamp">ACCESS DENIED</span><h2>관리자 권한이 없음</h2><p>로그인은 됐지만 관리자 이메일 allowlist에 포함되지 않았거나, 아직 서버 환경값이 설정되지 않았음.</p></div></div>; return <div className="page-stack admin-placeholder"><PageIntro eyebrow="PRIVATE AREA" title="새 글 쓰기" copy="제목, 분류, 태그, Markdown 본문만 적으면 됨." /><div className="admin-editor"><label>제목<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="예: 이거 만들다가 또 망함" /></label><div className="admin-editor-row"><label>카테고리<select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.filter((item) => !item.parentId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>태그<input value={tags} onChange={(event) => setTags(event.target.value)} placeholder="#개발 #생각" /></label></div><label>본문<textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder="# 제목\n\n마크다운으로 편하게 작성하면 됨." rows={12} /></label><div className="admin-actions"><button className="button-link" type="button" onClick={() => setPreview((value) => !value)}>{preview ? "작성으로 돌아가기" : "미리보기"}</button><button className="button-link muted-button" type="button" disabled>게시 준비 중</button></div>{preview ? <div className="admin-live-preview"><p className="eyebrow">PREVIEW</p><h2>{title || "제목 없음"}</h2><p>{body || "본문을 적으면 여기에 미리보기가 나옴."}</p></div> : null}</div><p className="admin-footnote">※ 현재 샘플 저장소 단계라 게시 버튼은 비활성화되어 있음. 이후 D1 또는 Firestore repository의 관리자 API에 연결하면 됨.</p></div>; }
function PageIntro({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <header className="page-intro"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></header>; }
function PostCard({ post }: { post: Post }) { const category = getPostCategory(post); return <Link className="post-card" href={`/post/${post.slug}`}><div className="post-card-top"><span className="category-label"><i style={{ backgroundColor: category?.accent }} />{category?.name ?? post.category}</span><time>{formatDate(post.createdAt)}</time></div><h3>{post.title}</h3><p>{getExcerpt(post.content)}</p><div className="post-card-bottom"><span>{post.tags.slice(0, 2).map((tag) => `#${tag}`).join(" ")}</span><span className="card-arrow">↗</span></div></Link>; }
function EmptyState({ text }: { text: string }) { return <div className="empty-state"><span>∅</span><p>{text}</p></div>; }
function NotFoundPage() { return <div className="page-stack not-found"><p className="eyebrow">404 / NOTHING HERE</p><h1>이 페이지는 아직 안 만듦.</h1><Link className="button-link" href="/">홈으로</Link></div>; }

function MarkdownContent({ source }: { source: string }) { useEffect(() => { const mathJax = (window as Window & { MathJax?: { typesetPromise?: () => Promise<void> } }).MathJax; void mathJax?.typesetPromise?.(); }, [source]); const blocks = source.trim().split(/\n{2,}/); return <div className="markdown-content">{blocks.map((block, index) => { const key = `${index}-${block.slice(0, 12)}`; if (block.startsWith("```")) { const lines = block.split("\n"); const language = lines[0].replace("```", "").trim(); return <pre key={key} data-language={language}><code>{lines.slice(1, -1).join("\n")}</code></pre>; } if (/^#{1,3} /.test(block)) { const level = block.match(/^#+/)?.[0].length ?? 2; const text = block.replace(/^#{1,3} /, ""); if (level === 1) return <h2 key={key}>{renderInline(text)}</h2>; return <h3 key={key}>{renderInline(text)}</h3>; } if (/^> /.test(block)) return <blockquote key={key}>{renderInline(block.replace(/^> /, ""))}</blockquote>; if (/^(?:- |\* )/.test(block)) return <ul key={key}>{block.split("\n").map((line) => <li key={line}>{renderInline(line.replace(/^(?:- |\* )/, ""))}</li>)}</ul>; if (block.startsWith("\\[") || block.startsWith("$$")) return <div className="math-block" key={key}>{block}</div>; if (/^!\[.*\]\(.*\)$/.test(block)) { const match = block.match(/^!\[(.*)\]\((.*)\)$/); return match ? <figure key={key}><img src={match[2]} alt={match[1]} /><figcaption>{match[1]}</figcaption></figure> : null; } return <p key={key}>{block.split("\n").map((line, lineIndex) => <span key={`${key}-${lineIndex}`}>{lineIndex ? <br /> : null}{renderInline(line)}</span>)}</p>; })}</div>; }
function renderInline(text: string) { const tokens = text.split(/(\*\*[^*]+\*\*|`[^`]+`|\[[^\]]+\]\([^\)]+\)|\\\([^\)]+\\\)|\$[^$]+\$)/g).filter(Boolean); return tokens.map((token, index) => { const key = `${token}-${index}`; if (token.startsWith("**") && token.endsWith("**")) return <strong key={key}>{token.slice(2, -2)}</strong>; if (token.startsWith("`") && token.endsWith("`")) return <code key={key}>{token.slice(1, -1)}</code>; const link = token.match(/^\[([^\]]+)\]\(([^\)]+)\)$/); if (link) return <a key={key} href={link[2]} target="_blank" rel="noreferrer">{link[1]}</a>; if (token.startsWith("\\(") || token.startsWith("$")) return <span className="math-inline" key={key}>{token}</span>; return <span key={key}>{token}</span>; }); }
